[package]
name = "matrices"
version = "0.1.0"
authors = ["Josh White <josh@animind.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
